sudo: required
dist: trusty

language: haxe

haxe:
  - 4.1.2
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - npm i
  - npm run lix use haxe 4.1.2
  - npm run haxe build.hxml


# deploy:
#   - provider: script
#     haxe: 4.1.2
#     script: bash ./release_haxelib.sh $HAXELIB_PWD
#     on:
#       tags: true